In [8]:
import torch

# Заполнить значениями
t = torch.full((1,4),5)

# Диапазон с шагом
t2 = torch.arange(-5,0,2)

# Создать интервал с разбиением
t3 = torch.linspace(1,2,10)

print(t)
print(t2)
print(t3)

tensor([[5, 5, 5, 5]])
tensor([-5, -3, -1])
tensor([1.0000, 1.1111, 1.2222, 1.3333, 1.4444, 1.5556, 1.6667, 1.7778, 1.8889,
        2.0000])


In [12]:
#Фиксация датчика случайных чисел
torch.manual_seed(0)

# Случайные числа
t4 = torch.rand(2,3)

# Случайные числа с норм распределением
t5 = torch.randn(2,3)
print(t4)
print(t5)


tensor([[0.4963, 0.7682, 0.0885],
        [0.1320, 0.3074, 0.6341]])
tensor([[ 1.2645, -0.6874,  0.1604],
        [-0.6065, -0.7831,  1.0622]])


In [20]:
# Inplace методы _
t5 = torch.FloatTensor(2,4)
t5.fill_(5)

# случайные дискретные значения
t5.random_(0,5)
print(t5)

# Случайные непрерывные значения
t5.uniform_(0,1)
print(t5)

# Случайные гаусовские значения
t5.normal_(0,1)
print(t5)

tensor([[3., 1., 4., 1.],
        [1., 0., 2., 4.]])
tensor([[0.8802, 0.0012, 0.5936, 0.4158],
        [0.4177, 0.2711, 0.6923, 0.2038]])
tensor([[-1.9513,  0.4186,  3.3214,  0.8764],
        [ 1.2345, -1.1642, -0.0240,  0.6480]])
