In [ ]:
import torch
# Заполнение 1
t0 = torch.ones(2,3)

# Заполнить значениями
t = torch.full((1,4),5)

# Диапазон с шагом
t2 = torch.arange(-5,0,2)

# Создать интервал с разбиением
t3 = torch.linspace(1,2,10)

print(t0)
print(t)
print(t2)
print(t3)

tensor([[5, 5, 5, 5]])
tensor([-5, -3, -1])
tensor([1.0000, 1.1111, 1.2222, 1.3333, 1.4444, 1.5556, 1.6667, 1.7778, 1.8889,
        2.0000])


In [12]:
#Фиксация датчика случайных чисел
torch.manual_seed(0)

# Случайные числа
t4 = torch.rand(2,3)

# Случайные числа с норм распределением
t5 = torch.randn(2,3)
print(t4)
print(t5)


tensor([[0.4963, 0.7682, 0.0885],
        [0.1320, 0.3074, 0.6341]])
tensor([[ 1.2645, -0.6874,  0.1604],
        [-0.6065, -0.7831,  1.0622]])


In [20]:
# Inplace методы _
t5 = torch.FloatTensor(2,4)
t5.fill_(5)

# случайные дискретные значения
t5.random_(0,5)
print(t5)

# Случайные непрерывные значения
t5.uniform_(0,1)
print(t5)

# Случайные гаусовские значения
t5.normal_(0,1)
print(t5)

tensor([[3., 1., 4., 1.],
        [1., 0., 2., 4.]])
tensor([[0.8802, 0.0012, 0.5936, 0.4158],
        [0.4177, 0.2711, 0.6923, 0.2038]])
tensor([[-1.9513,  0.4186,  3.3214,  0.8764],
        [ 1.2345, -1.1642, -0.0240,  0.6480]])


In [22]:
# Изменеие формы
x = torch.arange(27)
d = x.reshape(3,3,3)
d1 = x.view(3,3,3)

# Изменение размера
d2 = x.resize_(2,2)

# Преобразовать в  вектор
d3 = x.ravel()

# Смена осей для размерностей > 2
d.permute(1,0,2)

# Транспонирование
d.mT

print(d1)
print(d2)
print(d3)

tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]],

        [[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]]])
tensor([[0, 1],
        [2, 3]])
tensor([0, 1, 2, 3])


In [ ]:
# Добавление осей и удаление осей (только с 1 элементом!)
x_test = torch.arange(32).view(8,2,2)

x_test4 = torch.unsqueeze(x_test, dim=0)

# Добавить последнюю ось
x_test5 = torch.unsqueeze(x_test, dim=-1)

# Удалить ось
x_test5.squeeze_(dim=-1)

print(x_test.shape)
print(x_test4.shape)
print(x_test5.shape)


torch.Size([8, 2, 2])
torch.Size([1, 8, 2, 2])
torch.Size([8, 2, 2])


In [ ]:
# 1
import torch

t1 = torch.zeros((4,8,2),dtype=torch.int8)
t2 = torch.ones((1,9),dtype=torch.int8)
t3 = torch.eye(5,4, dtype=torch.int8)
t4 = torch.full((2,7,1,5),-5,dtype=torch.int8)


In [99]:
# 2
t1 = torch.arange(2,11,dtype=torch.float32)
t2 = torch.arange(21.,25.,0.5,dtype=torch.float32).view(1,8)
t3 = torch.arange(0., -2., -0.2 ).view(5,2)

In [107]:
# 3
t1 = torch.linspace(3,7,3)
t2 = torch.linspace(9,-9,10)
t3 = torch.linspace(5, -5, 5).view(-1,1)

t3

tensor([[ 5.0000],
        [ 2.5000],
        [ 0.0000],
        [-2.5000],
        [-5.0000]])

In [ ]:
# 4
t1 = torch.rand(21, dtype=torch.float32)  # равномерно распределенных
t2 = torch.randint(low=-5, high=6, size=(3, 5), dtype=torch.int16) # равномерно распределенны
t3 = torch.randn(64, 128, dtype=torch.float64) #нормально распределенных

# или
t1 = torch.rand(21,dtype=torch.float32)
t2 = torch.ones((3,5),dtype=torch.int16).random_(-5,6)
t3 = torch.ones((64,128),dtype=torch.float64).normal_()
 

tensor([[ 3,  5,  2, -4, -3],
        [-5, -1, -1,  1, -5],
        [-4, -3, -4, -2, -3]], dtype=torch.int16)

In [ ]:
# 8
t1 = torch.FloatTensor(3,10,2).uniform_(-2,10)
t2 = torch.FloatTensor(123).random_(13,20)
t3 = torch.FloatTensor(8,1024).normal_(23,50)

torch.float32

In [135]:
# 9
import torch

t = torch.empty(128).fill_(13)
t2 = t.view(8, 16)
t3 = t.view(-1, 32)
t4 = t.reshape(2, 4, 16)
t.resize_(16, 4)

t[0, 0] = 5

In [ ]:
# 10
t_indx = torch.linspace(1, 64, 64,dtype=torch.int64).view(2,-1)

# или
t_indx = torch.arange(1, 65, 1,dtype=torch.int64).view(2,-1)

t_indx.shape

torch.Size([2, 32])

In [162]:
# 11
tr = torch.arange(-10,9,2 ,dtype=torch.int32).view(5,2)
tr_r = tr.mT

In [167]:
# 13
t1 = torch.empty(3, 2, 10).fill_(5)
t2 = torch.empty(1, 10, 1, 7, 1).fill_(-1)

t1.unsqueeze_(0)
t2.squeeze_()
t2.shape

torch.Size([10, 7])