In [6]:
import torch

a = torch.arange(12)
a[0] # возврат тензора
a[0].item() # возврат значения

a[2:4] # interval

tensor([2, 3])

In [ ]:
# High dim tensors
x = torch.arange(27).view(3,-1)
x[:,::2] # С шагом 2
x[...,1] # Замена полных срезов

tensor([ 1, 10, 19])

In [ ]:
# Списочная индексация
a = torch.arange(1,9)
b = a[[0,1,4,6]] # создается копия 

tensor([1, 2, 5, 7])

In [ ]:
indx = torch.IntTensor([0,0,1,1,2,2,2])
c = a[indx]

indx_bool = torch.BoolTensor([True,False,True,True, True,False,True,True]) # маска
d = a[indx_bool]
d

tensor([1, 3, 4, 5, 7, 8])

In [32]:
# 1
tr = torch.arange(32,dtype=torch.int32)
tr[[0,-1]] = -1
tr

tensor([-1,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, -1],
       dtype=torch.int32)

In [47]:
# 2
lst = list(map(float, input().split())) # список в программе не менять
tr = torch.FloatTensor(lst)
tr_2 = tr[::2]
print(*tr_2.numpy())

# or
print(" ".join ([str(round(i.item(),1)) for i in tr_2]))

1.0
1.0


In [50]:
# 3
import torch
t1 = torch.empty(12, dtype=torch.int32)
t2 = torch.arange(-2, 3, dtype=torch.int32)

t1[1:5] = t2[:4]

res_1 = t1[2:4]
res_2 = t2[::2]
res_3 = t1[1:]
res_4 = t2[-3:-1]


In [65]:
# 4
tr = torch.IntTensor(10).fill_(0)
tr[1::2] = 100
print(*tr.tolist())

0 100 0 100 0 100 0 100 0 100


In [86]:
# 5
import torch

# списки lst_1 и lst_2 в программе не менять
lst_1 = [1,2,3,4,5,6,7,8,9]
lst_2 = [7,6,5,4]

t1 = torch.tensor(lst_1, dtype=torch.int32)
t2 = torch.tensor(lst_2, dtype=torch.int32)

t1[1:len(lst_2)+1] = t2
print(*t1.tolist())

1 7 6 5 4 6 7 8 9


In [ ]:
# 6
t1  = torch.arange(1,13,dtype=torch.int16).view(3,4)
t2 = torch.arange(10,130,10,dtype=torch.int16).view(3,4)
t3 = torch.arange(-1,-13,-1,dtype=torch.int16).view(3,4)
tr3d  = torch.stack((t1,t2,t3))
tm = tr3d[1]
tm


tensor([[ 10,  20,  30,  40],
        [ 50,  60,  70,  80],
        [ 90, 100, 110, 120]], dtype=torch.int16)

In [ ]:
# 7
lst = list(map(int, input().split())) # список lst в программе не менять
tr3d = torch.tensor(lst,dtype=torch.int16).view(3,3,4)
t_res = tr3d[:,[1],:].view(3,4)

# Если не создавать копию то
lst = list(map(int, input().split())) # список lst в программе не менять
tr3d = torch.tensor(lst,dtype=torch.int16).view(3,3,4)
t_res = tr3d[:,1,:].view(3,4)

print(tr3d.shape)
print(t_res.shape)


torch.Size([3, 3, 4])
torch.Size([3, 4])


In [149]:
# 8 
import torch

lst = list(map(int, input().split())) # список lst в программе не менять
tr3d = torch.tensor(lst,dtype=torch.int32).view(3,3,4)
t_res = tr3d[:,:,1].view(3,3).permute(1,0)

# or
tr3d = torch.tensor(lst, dtype=torch.int32).view(3, 3, 4)
t_res = tr3d[..., 1].permute(1, 0)


In [ ]:
# 9
lst = [8, 11, -4, 2, -1, -2, 0, -1]
tr  = torch.tensor(lst, dtype=torch.int32)

t_pos = tr[tr>0]
t_pos


tensor([ 8, 11,  2], dtype=torch.int32)

In [ ]:
# 10

lst = [11,18,5,7,5,11,1]
tr  = torch.tensor(lst, dtype=torch.int32)

t_indx = tr[[1,1,2,1,0]]



tensor([18, 18,  5, 18, 11], dtype=torch.int32)

In [175]:
# 11
lst = [-1,2,-4,5,1,5,-1,2,3,3,5,-2,-3,-5,-3,-1]
tr  = torch.tensor(lst, dtype=torch.int32)
mask = (tr>=-2) & (tr<=2)
t_res = tr[mask]
t_res


tensor([-1,  2,  1, -1,  2, -2, -1], dtype=torch.int32)