In [1]:
import torch


In [ ]:
# Elementwise operations
a = torch.IntTensor([1,2,3,4])
b = torch.IntTensor([5,6,7,8])

a+b

tensor([ 6,  8, 10, 12], dtype=torch.int32)

In [ ]:
# Translating tensors
c = torch.ones(2,4)
a+c

tensor([[2., 3., 4., 5.],
        [2., 3., 4., 5.]])

In [9]:
# 1 
tr = torch.arange(-5,2.0,0.5, dtype=torch.float32)
tr.add_(11).mul_(2.5)
tr

tensor([15.0000, 16.2500, 17.5000, 18.7500, 20.0000, 21.2500, 22.5000, 23.7500,
        25.0000, 26.2500, 27.5000, 28.7500, 30.0000, 31.2500])

In [16]:
# 2
inp = "2 6 2 10 9 6 6 9 10 5 9 2"
lst = list(map(int, inp.split()))

tr = torch.tensor(lst, dtype=torch.int32)

tr_res = tr[tr>5]%2
# or
tr_res = tr[tr>5].fmod(2)



print(tr_res)
print(tr)

tensor([0, 0, 1, 0, 0, 1, 0, 1], dtype=torch.int32)
tensor([ 2,  6,  2, 10,  9,  6,  6,  9, 10,  5,  9,  2], dtype=torch.int32)


In [ ]:
# 3

lst_1 = list(map(int, "6 -1 -4 -5 1 8 -4 14 -5 10 9 18 12 18 11".split()))
lst_2 = list(map(int, "2 2 2 3 4 5 2 1 3 1".split()))

tr_1 = torch.tensor(lst_1,dtype=torch.int32)
tr_2 = torch.tensor(lst_2,dtype=torch.int32)

# sz = min(len(tr_1), len(tr_2))
# tr_1[:sz].pow_(tr_2[:sz])
# tr_1.resize_(sz)

# or
sz = min(tr_1.numel(), tr_2.numel())
tr_1[:sz].pow_(tr_2[:sz])
tr_1.resize_(sz)

tensor([   36,     1,    16,  -125,     1, 32768,    16,    14,  -125,    10],
       dtype=torch.int32)

In [1]:
#4
import torch
lst = list(map(float, "0.8 -5.0 -1.3 -0.7 1.5 -1.3 4.0 -3.6 -0.2 -4.6 -3.4 3.3 4.9 -2.6 3.9 -0.5".split())) # список lst в программе не менять

t_mask = torch.ones(len(lst),dtype=torch.int8)
t_mask[1::2]*=-1

tr = torch.Tensor(lst)
tr*=t_mask.to(dtype=torch.float32)
print(*tr.numpy())
tr.dtype


0.8 5.0 -1.3 0.7 1.5 1.3 4.0 3.6 -0.2 4.6 -3.4 -3.3 4.9 2.6 3.9 0.5


torch.float32

In [7]:
import torch

t1 = torch.arange(1, 16, dtype=torch.int32).view(-1, 3)
t2 = torch.rand(3)
t3 = torch.randint(1, 10, (4, ), dtype=torch.int32)

res_1 = t1 + t2
res_2 = t2 * t1
# res_3 = t1 // t3
# t1 *= t2
t2 -= t3[:3]

In [8]:
import torch

a = torch.empty(3, 2).normal_(0, 2)
b = torch.randn(3)

res_1 = a.mT + b
res_2 = a.sub_(b[:2])
res_2[1, 1] = 100
res_3 = a.mT.mul_(b) + 3.0
res_3[-1, -1] = 0

In [ ]:
# 8
lst = list(map(int, "76 72 1 18 79 78 43 93 44 69 7 88 23 16 64 60 3 74 41 44 77 76 9 22".split())) # список lst в программе не менять
tr = torch.tensor(lst, dtype=torch.int32).view(2,-1)
t_even = tr[0,tr[0] % 2 ==0]
t_odd = tr[1,tr[1] % 2 !=0]
print(t_even)
print(t_odd)


tensor([76, 72, 18, 78, 44, 88], dtype=torch.int32)
tensor([23,  3, 41, 77,  9], dtype=torch.int32)


In [67]:
# 9
current_tm = int(19485) # переменную current_tm в программе не менять
t_time = torch.IntTensor(4).fill_(current_tm)

t_time[1]//=3600
t_time[2]//=60
t_time[2]%=60
t_time[3]%=60


# hrs = current_tm // 3600
# mins = (current_tm // 60) % 60
# sec = current_tm % (hrs * 3600 + mins * 60)

# t_time[0] = current_tm
# t_time[1] = hrs
# t_time[2] = mins
# t_time[3] = sec

# torch.IntTensor(4)
t_time

tensor([19485,     5,    24,    45], dtype=torch.int32)

In [ ]:
# 10
lst = list(map(int, "5 4 2 7 3".split()))

targets = torch.tensor(lst, dtype=torch.int32)
t_onehot = torch.zeros(targets.numel(),max(targets).item()+1,dtype=torch.int8)

for i, val in enumerate(targets):
    t_onehot[i,val] =1

# or
t_onehot[torch.arange(targets.numel()), lst] = 1

t_onehot

tensor([[0, 0, 0, 0, 0, 1, 0, 0],
        [0, 0, 0, 0, 1, 0, 0, 0],
        [0, 0, 1, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 1],
        [0, 0, 0, 1, 0, 0, 0, 0]], dtype=torch.int8)

torch.Size([5, 7])