In [2]:
import torch

x = torch.tensor([2.0] , requires_grad=True) # добавление узов за вычисление производных
y = torch.tensor([-4.0], requires_grad=True)

f = (x+y) ** 2 + 2*x*y
f.backward()

print(f)

print(x.data, x.grad)
print(y.data, y.grad)


tensor([-12.], grad_fn=<AddBackward0>)
tensor([2.]) tensor([-12.])
tensor([-4.]) tensor([0.])


In [ ]:
# 4
import torch

d = 4.5
t = torch.tensor([d],requires_grad=True)
f = 3*t*t + 5*t - 2

f.backward()
print(t.grad)

tensor([32.])


In [ ]:
# 5
import torch

g = 8.5
d = 12.7

g_tensor = torch.tensor([g], requires_grad=True)
t = torch.tensor([d], requires_grad=True)

f = - (g_tensor * t*t)/2 + g * torch.exp(-t) + 1.5
f.backward()
print(t.grad)




tensor([-107.9500])


In [ ]:
# 6 

import torch

xx = float(2.5) # значение xx в программе не менять
x = torch.tensor(xx, dtype=torch.float32)

x0, x1, x2, x3 = map(float, "0.12 0.5 -2.3 0.1".split()) # переменные x0, x1, x2, x3 в программе не менять

w0 = torch.tensor(x0, dtype=torch.float32, requires_grad=True)
w1 = torch.tensor(x1, dtype=torch.float32, requires_grad=True)
w2 = torch.tensor(x2, dtype=torch.float32, requires_grad=True)
w3 = torch.tensor(x3, dtype=torch.float32, requires_grad=True)

def fx(x):
    return torch.tensor([0.5 * x *x - 2 * x - 5], dtype=torch.float32, requires_grad=True)


appr = w0 + x1 * w1 + w2 *x2 **2  + w3*x3**3
L = (appr - fx(x))**2
L.backward()



In [7]:
# 7
import torch

x0, x1, x2, x3 = map(float, "0.12 0.5 -2.3 0.1".split()) # переменные x0, x1, x2, x3 в программе не менять

coords_x = torch.arange(-4, 6, 0.1) # точки интервала [-4; 6) с шагом 0.1 (тензор в программе не менять)

w0 = torch.tensor(x0, dtype=torch.float32, requires_grad=True)
w1 = torch.tensor(x1, dtype=torch.float32, requires_grad=True)
w2 = torch.tensor(x2, dtype=torch.float32, requires_grad=True)
w3 = torch.tensor(x3, dtype=torch.float32, requires_grad=True)

def fx(x):
    return -0.7 *x - 0.2 *x**2 + 0.05 *x**3 - 0.2 * torch.cos(3 * x) + 2

pred = w0 + w1 * coords_x + w2 * coords_x**2 + w3 * coords_x**3
Q = torch.mean((pred - fx(coords_x))**2)
Q.backward()
